### ISSUE TITLE
ninja_syntax.py license

### ISSUE THREAD

**Issue by rightfold** [martine/ninja#1005]
Is misc/ninja_synax.py under the same license as Ninja proper, and if I distribute misc/ninja_syntax.py with my software (but no other part of Ninja), do I need to attach the Apache license?

**Comment by nico** [comment]
See this post on the mailing list: https://groups.google.com/d/msg/ninja-build/PceLYvPJpKY/5YmjhZJ8Q3UJ

**Comment by nico** [comment]
(and maybe https://groups.google.com/d/msg/ninja-build/PceLYvPJpKY/5YmjhZJ8Q3UJ too)
