### ISSUE TITLE
Mark output dirty if .d file doesn't match

### ISSUE THREAD

**Issue by rgeary1** [martine/ninja#417]
I can generate ninja files with either fully resolved or relative paths. Both builds work with a clean build, but if I switch between generator types and don't clean, then I get a fatal error :
ninja: error: expected depfile 'obj/release/lvm.o.d' to mention 'obj/release/lvm.o', got '/spare/local/rgeary/inet/premake-dev-rgeary/obj/release/lvm.o'

If the first line of the .d file is not the expected file, ninja should always rebuild the file.

(This behaviour is observed on linux with the latest ninja/master code)

**Comment by nico** [comment]
https://github.com/martine/ninja/pull/930 implements this change. Unless someone shouts, I'll merge that in a few days.
