### ISSUE TITLE
Commit 395f4c broke Cygwin compatibility

### ISSUE THREAD

**Issue by RedX2501** [martine/ninja#806]
Commit [Prepared load (-l N) support for windows.](https://github.com/martine/ninja/commit/395f4c8873e784131dab6ee67133f80d03b23e4a)  Uses the FILETIME struct which cygwin does not provide.

Just changing the #ifdef does not fix it as `loadavg` is not provided by cygwin also.

A temporary change is to return to the previous version for cygwin:

    #ifdef __CYGWIN__
    double GetLoadAverage() {
        return 0.0;
    }
    #elif defined(_WIN32)
    ....
    #endif

**Comment by martell** [comment]
close?

**Comment by kwesolowski** [comment]
@RedX2501 would be best person to confirm it is resolved, but according to my tests it is.

**Comment by RedX2501** [comment]
I just checked out master (a48434493d69085aa6fc0c002180ace555cad592 Mon Sep 7 16:52:25 2015) and it seems to be fixed indeed.

**Comment by nico** [comment]
Thanks!
