### ISSUE TITLE
configure script produces fatal error C1034: cstdio: no include path set

### ISSUE THREAD

**Issue by huywang** [martine/ninja#895]
When I modified .cc file ,ninja works well, this .cc file will be compiled. But when I modified a .h file, ninja show no work to do.

BTW, when I build ninja with the src, some error happened:
F:\source\ninja\ninja>python ./configure.py --bootstrap
bootstrapping ninja...
warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/
*.in.cc will not affect your build.
build.cc
f:\source\ninja\ninja\src\build.h(18) : fatal error C1034: cstdio: no include pa
th set
when running:  cl /nologo /Zi /W4 /WX /wd4530 /wd4100 /wd4706 /wd4512 /wd4800 /w
d4702 /wd4819 /wd4355 /wd4091 /GR- /wd4267 /DNOMINMAX /D_CRT_SECURE_NO_WARNINGS
/D_VARIADIC_MAX=10 /DNINJA_PYTHON="python.exe" /Ox /DNDEBUG /GL -c src\build.cc
/Fobuild\build.obj
Traceback (most recent call last):
  File "./configure.py", line 461, in <module>
    objs += cxx(name)
  File "./configure.py", line 262, in cxx
    return n.build(built(name + objext), 'cxx', src(name + '.cc'), **kwargs)
  File "./configure.py", line 148, in build
    self._run_command(self._expand(cmd, local_vars))
  File "./configure.py", line 169, in _run_command
    subprocess.check_call(cmdline, shell=True)
  File "E:\depot_tools\python276_bin\lib\subprocess.py", line 540, in check_call

    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cl /nologo /Zi /W4 /WX /wd4530 /wd4100 /
wd4706 /wd4512 /wd4800 /wd4702 /wd4819 /wd4355 /wd4091 /GR- /wd4267 /DNOMINMAX /
D_CRT_SECURE_NO_WARNINGS /D_VARIADIC_MAX=10 /DNINJA_PYTHON="python.exe" /Ox /DND
EBUG /GL -c src\build.cc /Fobuild\build.obj' returned non-zero exit status 2

How do I solve this. My enviroment is Win7 64bit, vs2013 community

**Comment by sgraham** [comment]
Did you run vcvarsall before building? It looks like it can't find standard
headers.

**Comment by martine** [comment]
It looks like you reported two issues in this bug.  Let's make this one about the configure failure.  Can you open another about the problem you encountered with rebuilding?

**Comment by huywang** [comment]
Run vcvarsall will solve this ,thanks!
