### ISSUE TITLE
crash when referencing variable in its definition

### ISSUE THREAD

**Issue by nico** [martine/ninja#902]
rule b
      command = $command

    build a.o: b

ninja -n -f afl-ninja-out/hangs/id\:000005\,src\:001151\,op\:havoc\,rep\:4 
Segmentation fault: 11

Found by afl-fuzz.

**Comment by sgraham** [comment]
Wow! Neat tool.

**Comment by nico** [comment]
(Yeah! I wrote a custom dictionary for ninja keywords for it. I wanted to run it without the dictionary this night and see if that actually finds less than yesterday's run with one – if so, I should probably put the dict somewhere below misc/. It also found the three known bugs with dependency cycles with duplicate output edges that took me a long time to find manually.)

**Comment by nico** [comment]
I gave this a look, it's a bit annoying to fix. See the commit messages of these two things:

https://github.com/martine/ninja/compare/martine:master...nico:cyclefix1?expand=1
https://github.com/martine/ninja/compare/martine:master...nico:cyclefix2?expand=1

**Comment by nico** [comment]
With this fixed, afl-fuzz stopped finding crashes as far as I can tell (but I only ran it for ~6h so far; I'll run it some more).
