### ISSUE TITLE
ninja install for a single target ?

### ISSUE THREAD

**Issue by martell** [martine/ninja#932]
When using ninja to build llvm i discovered I can't do 
```ninja install clang``` or ```ninja clang install``` to only install clang

We can do this with gnu make by cd to the correct dir as there is a makefile in each folder
and by just doing make install.
```cd tools/clang```
```make install```

Ninja files are only in the root build folder making this impossible.

I don't know much about the code base but could this be implemented in ninja somehow?

**Comment by nico** [comment]
llvm could have a `install-clang` target (like they have `check`, `check-clang`). I don't think there's a good way to do this in ninja itself.

**Comment by martell** [comment]
They don't and the consensus from them is that the should be a feature of the build system.
gnu make offers this and this is a big step backwards :(

http://stackoverflow.com/questions/17164731/installing-only-one-target-and-its-dependencies-out-of-a-complex-project-with
