### ISSUE TITLE
"[stuck]" without duplicate rules

### ISSUE THREAD

**Issue by nico** [martine/ninja#934]
Here's a "stuck" repro without duplicate rules (!):

    rule cg
       command = touch $out; touch b;
    
    build a b: cg c
    build c: cg a
    
    $ ninja 
    ninja: build stopped: stuck [this is a bug].

(Originally reported in a comment in #867. https://github.com/martine/ninja/issues/867#issuecomment-65918850 there suggests a fix, but it's possible that it's not a good fix.)

**Comment by nico** [comment]
Even simpler:

    rule ct
      command = cat $in > $out
    build foo bar: ct foo

(found by afl-fuzz when I replaced the "[stuck]" printf with a deliberate crash)

**Comment by martine** [comment]
It must be the multiple outputs, then?

**Comment by nico** [comment]
Yes, apparently there's a bug when a cycle is entered via an edge with multiple outputs, from an output not participating in the cycle – ninja fails to detect that cycle currently.

**Comment by nico** [comment]
I think the Right Fix here is to let `Plan::CheckDependencyCycle()` look for a cycle of Edges, not Nodes. `want_` works on Edges, so the cycle checker should too.

Printing the cycle still needs to output Node paths, so I need to play a bit and see how this is nicest (have a stack<pair<Edge*,Node*>>? Look at the in_edge of all the nodes in the stack<Node*>?)

**Comment by nico** [comment]
(I'm pretty with the fix I ended up checking in, it didn't really add much work and it was very localized.)
