### ISSUE TITLE
ninja gets confused by nul characters ('\0') in command standard output

### ISSUE THREAD

**Issue by plabath** [martine/ninja#941]
If a nul character appears in a command stdout, the rest of the output is not written. I believe ninja should write the output verbatim.
```
labath /tmp/nnn $ cat build.ninja 
rule CUSTOM_COMMAND
  command = $COMMAND
  description = Running a command which outputs nul characters

build do-it: CUSTOM_COMMAND
    COMMAND = cat test-file
labath /tmp/nnn $ hexdump -C test-file
00000000  44 6f 69 6e 67 20 73 6f  6d 65 20 77 6f 72 6b 2e  |Doing some work.|
00000010  2e 2e 2e 2e 0a 4e 6f 77  20 61 20 6e 75 6c 20 63  |.....Now a nul c|
00000020  68 61 72 61 63 74 65 72  20 61 63 63 69 64 65 6e  |haracter acciden|
00000030  74 61 6c 79 20 73 6c 69  70 73 20 69 6e 2e 2e 2e  |taly slips in...|
00000040  00 0a 4f 75 74 70 75 74  74 69 6e 67 20 61 20 76  |..Outputting a v|
00000050  65 72 79 20 69 6d 70 6f  72 74 61 6e 74 20 65 72  |ery important er|
00000060  72 6f 72 20 6d 65 73 73  61 67 65 20 77 68 69 63  |ror message whic|
00000070  68 20 77 69 6c 6c 20 6e  6f 74 20 62 65 20 76 69  |h will not be vi|
00000080  73 69 62 6c 65 2e 2e 2e  0a                       |sible....|
00000089
labath /tmp/nnn $ cat test-file
Doing some work.....
Now a nul character accidentaly slips in...
Outputting a very important error message which will not be visible...
labath /tmp/nnn $ ninja do-it
[1/1] Running a command which outputs nul characters
Doing some work.....
Now a nul character accidentaly slips in...labath /tmp/nnn $ 
```

**Comment by nico** [comment]
I can't reproduce this. (I have used a different text file with a few nul characters as reversing hexdump output isn't easy. Consider using xxd; it has a -r option which I could use.)

Which platform are you on? Which version of ninja are you using?

**Comment by nico** [comment]
I predict that you're using a ninja older than 1.4, which is where we fixed this (released 1.7 years ago). Please reopen if that's not true.

**Comment by plabath** [comment]
Yep, that's true, 1.3.4 :)
It still the latest on ubuntu 14.04. :(

**Comment by nico** [comment]
There are prebuilt binaries at https://github.com/martine/ninja/releases . ninja is just a single file, you can probably just copy that binary somewhere.

Maybe talk to whoever owns ninja on your distro to get it updated, seems like it's pretty behind :-/
