### ISSUE TITLE
DbgHelp.h is missing on Windows 8.1

### ISSUE THREAD

**Issue by unbornchikken** [martine/ninja#946]
Trying to build on Windows 8.1. SDK *.* installed, developer command promt opened. I get cannot open include file "DbgHelp.h" error when bootstrapper compiles minidump-win32.cc.

**Comment by sgraham** [comment]
After running vcvarsall, what's the output of "set INCLUDE"? It should include something like C:\Program Files (x86)\Windows Kits\8.1\include\um which is where DbgHelp.h should be.

**Comment by unbornchikken** [comment]
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC>vcvarsall

    C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC>set include   
    
    INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE;C:\Program Files (x86)\Windows Kits\8.0\include\shared;C:\Program Files (x86)\Windows Kits\8.0\include\um;C:\Program Files (x86)\Windows Kits\8.0\include\winrt;C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE;C:\Program Files (x86)\Windows Kits\8.0\include\shared;C:\Program Files (x86)\Windows Kits\8.0\include\um;C:\Program Files (x86)\Windows Kits\8.0\include\winrt;

- C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE
- C:\Program Files (x86)\Windows Kits\8.0\include\shared
- C:\Program Files (x86)\Windows Kits\8.0\include\um
- C:\Program Files (x86)\Windows Kits\8.0\include\winrt
- C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE
- C:\Program Files (x86)\Windows Kits\8.0\include\shared 
- C:\Program Files (x86)\Windows Kits\8.0\include\um
- C:\Program Files (x86)\Windows Kits\8.0\include\winrt;

**Comment by unbornchikken** [comment]
Ok, I can see now. My VC Developer Tool Command promp icon in this Metro start screen crap gave me a command promp with Windows SDK 8.0 headers configured instead of 8.1. Oh my.

**Comment by sgraham** [comment]
Yeah, that search is not so great. I get the "wrong version" of something pretty often. :/
