### ISSUE TITLE
patch for rsp file dir separators issue with arm cross compiler

### ISSUE THREAD

**Issue by joachim99** [martine/ninja#956]
On windows the command line length can be exceeded for big projects. Then ninja writes an rsp file (e.g. for the linker it will contain all object files).
The arm crosscompiler reads the rsp file but doesn't handle the backslash '\' dir separator correctly. It requires forward slashes '/'.
See also:
http://www.cmake.org/pipermail/cmake/2013-January/053362.html
You might argue the bug is in the cross compiler. Nevertheless the old compilers are out there. This patch provides a workaround. 

Please note that I have not tested the patch with other compilers yet. It might make sense to do the replacement only when a certain environment variable is set or a command line switch is given.

    diff --git a/src/build.cc b/src/build.cc
    index ccdb37f..397c5ae 100644
    --- a/src/build.cc
    +++ b/src/build.cc
    @@ -721,6 +721,11 @@ bool Builder::StartEdge(Edge* edge, string* err) {
       string rspfile = edge->GetUnescapedRspfile();
       if (!rspfile.empty()) {
         string content = edge->GetBinding("rspfile_content");
    +    for(size_t i=0; i<content.length(); ++i)
    +      {
    +         if (content[i]=='\\')
    +            content[i]='/';   // Arm cross compiler expects '/' as dir separator (arm-none-linux-gnueabi-g++.exe (Sourcery CodeBench Lite 2013.05-24) 4.7.3
    +      }
         if (!disk_interface_->WriteFile(rspfile, content))
           return false;
       }

**Comment by sgraham** [comment]
Hmm, I think ninja maintains the slash direction from the input. Are you certain the generator is emitting forward slashes if that's what the compiler wants?

**Comment by nico** [comment]
After the mess in #843, I'm pretty sure we don't want to convert backslashes to slashes in ninja.

It's possible that we don't write backslashes to rsp files correctly (maybe they're underescaped).

If your compiler can't handle backslashes, then make your generator write files with slashes. ninja should just let through what's in your build files. Ninja should write forward slashes to rsp files correctly.

**Comment by martine** [comment]
(Just to add, the patch above also has the problem where if the command-line flags include a meaningful slash, something like -DFOOBAR_PATH="C:\\Windows", then this code would mangle the value of the preprocessor define.)
