### ISSUE TITLE
Pool limit not being respected

### ISSUE THREAD

**Issue by sgraham** [martine/ninja#959]
In https://code.google.com/p/chromium/issues/detail?id=476053#c19 it seems that the depth of a pool is not being respected.

I don't have a repro though. I'm giving the brute force method a try by adding a crash for the case that seems to be happening and running under afl-fuzz.

**Comment by sgraham** [comment]
afl-fuzz didn't find it (yet?) unfortunately.

With https://github.com/martine/ninja/compare/master...sgraham:pool-2 and the input of https://dl.dropboxusercontent.com/u/116514/pool-crash.zip `ninja -C pool-crash -j1 -n` will abort() reliably for me.

**Comment by sgraham** [comment]
Oh wait, that repro isn't useful because it needs all the input .cc of course. Bleh.

**Comment by sgraham** [comment]
Got back to this a bit more. I still don't have a small repro and I feel like it should be easy to make one, but I haven't been able to. Here's my log of debugging a failing chrome case.

Get to a `stamp` with 3 inputs:
    gen/components/components_resources_new_stamp.d.stamp
    gen/components/grit/components_resources.h
    gen/components/components_resources.pak
outputting:
    obj/components/resources/components_resources_grit.stamp
wanted=true

set outputs_ready_ = true

Then something unrelated gets scheduled for the newly freed pool slot.

Then, NodeFinished for
    obj/components/resources/components_resources_grit.stamp
has 58 output edges, 55 stamps and 3 phony

2nd out_edge of the node has inputs of
    obj/components/resources/components_resource_grit.stamp
    obj/tools/grit/grit_sources.stamp
outputting:
    obj/components/resources/components_resources.inputdeps.stamp

both of those inputs pass AllInputsReady(), but want_e->second = false
-- means obj/components/resources/components_resources.inputdeps.stamp doesn't need to be built, but something it's an input for does need to be built.

Because of that, instead of calling Plan::ScheduleWork for the edge, we immediately call Plan::EdgeFinished. This then calls edge->pool()->EdgeFinished. But that edge has never been scheduled as far as the pool is concerned, so this breaks the pool use_count (can get way < 0).

Later uses then don't have a correct count so later edges that are otherwise scheduled correctly exceed the pool limit.

cc @riannucci @dpranke

**Comment by nico** [comment]
This is fixed on trunk, right?

**Comment by sgraham** [comment]
Yes, I forgot to put a magic xref in 962.
