### ISSUE TITLE
Build actions with pool=console sometimes fail to terminate

### ISSUE THREAD

**Issue by pcc** [martine/ninja#965]
To reproduce:

1. Check out LLVM and llgo (http://llvm.org/svn/llvm-project/llgo/trunk/README.TXT)
2. Apply http://reviews.llvm.org/D9495
3. Run cmake (>= 3.2) with ninja generator.
4. ninja check-libgo

Step 4 will not terminate.

**Comment by axw** [comment]
I've found that it does terminate, but takes a very long time to do so; around 4 minutes longer than it should. The child /bin/sh process is a zombie, and Ninja is stuck in ppoll (same happens with pselect).

**Comment by axw** [comment]
Turns out there was an orphaned process hanging onto the pipe's write end that gets created in Subprocess::Start in subprocess-posix.cc. Seems that the write end should just be closed in the console case. I'll send a PR, and someone can tell me if it's braindead.

**Comment by nico** [comment]
Does this still repro on trunk? #962 fixed a bug in pools, maybe that's related?

**Comment by axw** [comment]
@nico Yes, still repros. I pulled master yesterday.

**Comment by nico** [comment]
See https://github.com/martine/ninja/pull/967#issuecomment-116945038
