### ISSUE TITLE
Cannot build from source on Windows 8.1

### ISSUE THREAD

**Issue by eelstork** [martine/ninja#983]
Configuration: Windows 8.1 OEM, Python 2.7.10, 32 bits, intel based
Command: configure.py --bootstrap
Error:
  File "C:\Users\Thibaud\Documents\GitHub\ninja\configure.py", line 293, in <module>
    if platform.msvc_needs_fs():
  File "C:\Users\Thibaud\Documents\GitHub\ninja\configure.py", line 81, in msvc_needs_fs
    stderr=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

I know that I can use a binary instead. I suspect this is a configuration issue?

**Comment by sgraham** [comment]
You need to run a VS vcvarsall before running configure.py.

**Comment by eelstork** [comment]
The connection with vcvarsall is not obvious. Is this problem uncommon? Not worth documenting?

**Comment by nico** [comment]
That's needed to build anything in cmd.exe as far as I know. Alternatively, there's a "VS2013 x64 Native Tools Command Prompt" in start->All Programs->Visual Studio 2013->Visual Studio Tools which launches cmd.exe with that script already run.

I don't use Windows as my primary system so I don't know how well-known this is. I guess we could mention this in the readme.
