### ISSUE TITLE
[DOC] add info about meson build system

### ISSUE THREAD

**Issue by ignatenkobrain** [martine/ninja#992]
Hi, we are developing meson build system (parser for `meson.build` and `meson_options.txt` files with own DSL). Now we have our mime-type in xdg-mime-info database and our own language highlighter in GtkSourceView.

Reference: http://github.com/mesonbuild/
Reference: http://mesonbuild.com/

**Comment by nico** [comment]
I'm not sure what this issue is about. https://github.com/martine/ninja/wiki/List-of-generators-producing-ninja-build-files mentions meson.

**Comment by ignatenkobrain** [comment]
@nico hm, I looked at github.io page and couldn't find it. Can you update it?

**Comment by nico** [comment]
You mean http://ninja-build.org ? That doesn't have an exhaustive list of generators.  https://github.com/martine/ninja/wiki/List-of-generators-producing-ninja-build-files is that list, and it contains it.

(Maybe ninja-build.org could link to that wiki though.)
